### ISSUE TITLE
Inconsistent rom scanning

### ISSUE THREAD

**Issue by Jammintk** [ryandavidmercado/emu-hub#32]
ROM scanning is pretty inconsistent for me. NES/SNES/N64/GB/GBC/GBA/Dreamcast/PSX/PS2 all scan in fine, but I have folders full of games for other supported platforms. Genesis/Gamecube/NDS.

Maybe offering a manual option in settings in a future release for "add games by platform" with a directory entry field and a platform selector to add games not in expected folders would be a good failsafe for the auto-scan missing things.

Is EmuHub looking for games with specific extensions? Everything I have is stored in .zip. I'm also using pretty standard directory names for the platforms that aren't scanning in (megadrive/gcn/nds)

**Comment by rhythmerc** [comment]
Hi @Jammintk !

By default systems scan in the directory of their ID; you can check EmuHubConfig/defaults/systems.yml to see all the default systems and their configurations.

That explains GameCube & Megadrive; their IDs are "gc" and "genesis", respectively.

Think I'll add alternative directory scanning to the roadmap since this is a pretty reasonable request. In the meantime, you can specify romdir manually in EmuHubConfig/systems.yml (not the defaults one! user overrides and extensions go in the main EmuHubConfig directory):

```
- id: gc
  romdir: /full/path/to/gamecube
- id: genesis
  romdir: /full/path/to/megadrive
```

As for NDS, looks like I missed .zip in the fileExtensions for it! Will add in next release but you can add it in the same systems.yml file as your romdirs in the meantime:

```
- id: nds
  fileExtensions:
    - .zip
```

**Comment by ryandavidmercado** [comment]
Hi @Jammintk !

By default systems scan in the directory of their ID; you can check EmuHubConfig/defaults/systems.yml to see all the default systems and their configurations.

That explains GameCube & Megadrive; their IDs are "gc" and "genesis", respectively.

Think I'll add alternative directory scanning to the roadmap since this is a pretty reasonable request. In the meantime, you can specify romdir manually in EmuHubConfig/systems.yml (not the defaults one! user overrides and extensions go in the main EmuHubConfig directory):

```
- id: gc
  romdir: /full/path/to/gamecube
- id: genesis
  romdir: /full/path/to/megadrive
```

As for NDS, looks like I missed .zip in the fileExtensions for it! Will add in next release but you can add it in the same systems.yml file in the meantime with your romdirs in the meantime:

```
- id: nds
  fileExtensions:
    - .zip
```

**Comment by rhythmerc** [comment]
Closing due to lack of response; will add a new issue for adding alternative scan directories.
